language: ruby
# sudo: false

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4

script: "bundle exec rake clean spec cucumber"

addons:
  apt:
    update: true
    packages:
    - libjpeg-dev
    - libpng-dev
    - libgif-dev
    - ghostscript

before_install:
  - gem update --system
  - gem install bundler
  - sudo rm /etc/ImageMagick-6/policy.xml

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

matrix:
  fast_finish: true
  exclude:
    - gemfile: gemfiles/5.0.gemfile
      rvm: 2.1
